In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("C:/Users/asnav/Documents/MachineLearningProjects/resume_sreening/data/dataset.csv")
df.head()

,ID,Name,Role,Transcript,Resume,decision,Reason_for_decision,Job_Description
0,jasojo159,Jason Jones,E-commerce Specialist,"Interviewer: Good morning, Jason. It's great t...",Here's a professional resume for Jason Jones:\...,reject,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...
1,annma759,Ann Marshall,Game Developer,Interview Scene\n\nA conference room with a ta...,Here's a professional resume for Ann Marshall:...,select,Strong technical skills in AI and ML.,Help us build the next-generation products as ...
2,patrmc729,Patrick Mcclain,Human Resources Specialist,Interview Setting: A conference room in a medi...,Here's a professional resume for Patrick Mccla...,reject,Insufficient system design expertise for senio...,We need a Human Resources Specialist to enhanc...
3,patrgr422,Patricia Gray,E-commerce Specialist,Here's a simulated professional interview for ...,Here's a professional resume for Patricia Gray...,select,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...
4,amangr696,Amanda Gross,E-commerce Specialist,Here's the simulated interview:\n\nInterviewer...,Here's a professional resume for Amanda Gross:...,reject,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...

In [3]:
df.tail()

,ID,Name,Role,Transcript,Resume,decision,Reason_for_decision,Job_Description
10169,uppaup496,Diana Miller,Product Manager,Here's a simulated interview for a Product Man...,Here's a sample resume for Diana Miller:\n\n**...,reject,Unsatisfactory references or background check.,Here is a comprehensive job description for a ...
10170,uppaup497,Grace Taylor,UI Engineer,"**Interviewer:** Hi Grace, thank you for comin...",Here's a sample resume for Grace Taylor:\n\n**...,reject,Lack of relevant skills or experience.,Here is a sample job description for a UI Engi...
10171,uppaup498,Hank Brown,UI Engineer,Here's a simulated interview for a UI Engineer...,Here's a sample resume for Hank Brown:\n\n**Ha...,select,Growth mindset and adaptability.,Here is a job description for a UI Engineer ro...
10172,uppaup499,Diana Wilson,Data Engineer,Here's a simulated interview for a Data Engine...,Here's a sample resume for Diana Wilson:\n\n**...,reject,Lack of relevant skills or experience.,Here is a comprehensive job description for a ...
10173,uppaup500,Charlie Miller,Product Manager,Here's a simulated interview for a Product Man...,"Here's a sample resume for Charlie Miller, a P...",select,Strong cultural fit.,Here is a comprehensive job description for a ...

In [4]:
df.shape

(10174, 8)

In [5]:
df.columns

Index(['ID', 'Name', 'Role', 'Transcript', 'Resume', 'decision',
       'Reason_for_decision', 'Job_Description'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10174 entries, 0 to 10173
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10174 non-null  object
 1   Name                 10174 non-null  object
 2   Role                 10174 non-null  object
 3   Transcript           10174 non-null  object
 4   Resume               10174 non-null  object
 5   decision             10174 non-null  object
 6   Reason_for_decision  10174 non-null  object
 7   Job_Description      10174 non-null  object
dtypes: object(8)
memory usage: 636.0+ KB

In [7]:
df.describe()

,ID,Name,Role,Transcript,Resume,decision,Reason_for_decision,Job_Description
count,10174,10174,10174,10174,10174,10174,10174,10174
unique,10171,8677,45,10174,10174,2,539,3446
top,michmo483,Lucas,Data Scientist,Here's a simulated interview for a Product Man...,"Here's a sample resume for Charlie Miller, a P...",reject,Insufficient system design expertise for senio...,Join our team as a Product Manager and leverag...
freq,2,21,538,1,1,5114,730,103

In [8]:
df.isna().sum()

ID                     0
Name                   0
Role                   0
Transcript             0
Resume                 0
decision               0
Reason_for_decision    0
Job_Description        0
dtype: int64